# Generated by Django 4.1 on 2022-08-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_grupo_linea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='linea',
        ),
        migrations.AddField(
            model_name='grupo',
            name='linea',
            field=models.ManyToManyField(blank=True, null=True, to='core.linea'),
        ),
    ]
