# Generated by Django 4.1 on 2022-08-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_grupo_linea_grupo_linea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='linea',
            field=models.ManyToManyField(to='core.linea'),
        ),
    ]
