# Generated by Django 4.1 on 2022-08-29 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_grupo_linea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='linea',
        ),
        migrations.AddField(
            model_name='grupo',
            name='linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.linea'),
        ),
    ]
