# Generated by Django 4.1 on 2022-09-03 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_grupo_linea'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='fecha_eliminacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linea',
            name='fecha_eliminacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='linea',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='linea',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
