# Generated by Django 4.1 on 2022-09-04 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_ciudad_pais_provincia_empresa_ciudad_provincia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('nombres', models.CharField(max_length=200, unique=True)),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('latitud', models.CharField(blank=True, max_length=70, null=True)),
                ('longitud', models.CharField(blank=True, max_length=70, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefonos', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to='fotos/')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ciudad')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.pais')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.provincia')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ('-fecha', 'nombres'),
            },
        ),
    ]
