# Generated by Django 4.1 on 2022-09-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='ventas/clientes/'),
        ),
    ]
