# Generated by Django 4.1 on 2022-09-09 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_ciudad_usuario_empresa_usuario_grupo_usuario_and_more'),
        ('ventas', '0002_alter_cliente_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('alias', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('codigo_barra', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('stock_minimo', models.FloatField(default=0)),
                ('stock_maximo', models.FloatField(default=0)),
                ('foto', models.FileField(blank=True, null=True, upload_to='ventas/articulos/')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de Costo')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de Venta')),
                ('con_iva', models.BooleanField(default=True, verbose_name='Iva')),
                ('estado', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.grupo')),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.linea')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pago', models.CharField(choices=[('E', 'Efectivo'), ('C', 'Credito'), ('V', 'Paypal')], default='E', max_length=1)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('pagado', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True)),
                ('cambio', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ('-fecha', 'cliente'),
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ('nombres',), 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha',
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FacturaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('tasa_iva', models.FloatField(blank=True, default=0, null=True)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.articulo')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.factura')),
            ],
            options={
                'verbose_name': 'Factura Detalle',
                'verbose_name_plural': 'Factura Detalles',
                'ordering': ('factura',),
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.cliente'),
        ),
    ]
