# Generated by Django 4.1 on 2022-09-19 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0004_alter_articulo_alias_alter_articulo_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='cambio',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='pagado',
        ),
        migrations.AddField(
            model_name='articulo',
            name='fecha_eliminacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_eliminacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.cliente'),
        ),
    ]
