# Generated by Django 4.1 on 2022-09-19 00:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_remove_cliente_latitud_remove_cliente_longitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
