# Generated by Django 4.1.1 on 2022-09-25 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_ciudad_usuario_empresa_usuario_grupo_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateTimeField(auto_now=True)),
                ('nombres', models.CharField(max_length=200, unique=True)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('cargo', models.CharField(max_length=30)),
                ('telefonos', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to='ausentismos/empleados/')),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ciudad')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.pais')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.provincia')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ('nombres',),
            },
        ),
        migrations.CreateModel(
            name='PermisoVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateTimeField(auto_now=True)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('cargo', models.CharField(max_length=30)),
                ('telefonos', models.CharField(blank=True, max_length=10, null=True)),
                ('permiso', models.CharField(default='Vacaciones', max_length=10)),
                ('fecha_salida', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_reintegro', models.DateField(default=django.utils.timezone.now)),
                ('dias_permiso', models.CharField(default='30', max_length=2)),
                ('periodo', models.DateField(default=django.utils.timezone.now)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ausentismo.empleado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso Vacaciones',
                'verbose_name_plural': 'Permiso por Vacaciones',
                'ordering': ('empleado',),
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateTimeField(auto_now=True)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('cargo', models.CharField(max_length=30)),
                ('telefonos', models.CharField(blank=True, max_length=10, null=True)),
                ('motivo_permiso', models.CharField(blank=True, choices=[('P', 'Personal'), ('M', 'Medico')], default='P', max_length=10, null=True)),
                ('fecha_permiso', models.DateField(default=django.utils.timezone.now)),
                ('dias_permiso', models.CharField(max_length=2, unique=True)),
                ('periodo', models.DateField(default=django.utils.timezone.now)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ausentismo.empleado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'ordering': ('motivo_permiso', 'empleado'),
            },
        ),
    ]
